services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    command: standalone
    env_file:
      - path: .env
        required: false
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW_HOME: /opt/airflow
      PYTHONPATH: /opt/project/src
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .:/opt/project
      - ./dbt_profiles:/home/airflow/.dbt
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
