FROM apache/airflow:2.10.5-python3.12

COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

COPY pyproject.toml README.md /tmp/project/
COPY src /tmp/project/src
RUN pip install --no-cache-dir --no-deps /tmp/project
